Criação do script de criação da tabela
prefeiturasp/SME-CDEP pull request #10
Opened 2023-06-07 12:47 UTC by viniciusnyari

AB#95126

2023-06-07 21:19 UTC, rafalosiamcom requested changes

2023-06-07 21:19 UTC, rafalosiamcom commented on scripts/V1__USUARIO_CREATE.sql
> +	rf_codigo varchar(12) NULL,
não vai ter rf_codigo, é só login

2023-06-08 01:03 UTC, viniciusnyari commented on scripts/V1__USUARIO_CREATE.sql
> +	rf_codigo varchar(12) NULL,
Removido

2023-06-13 13:16 UTC, rafalosiamcom approved these changes

2023-06-13 13:16 UTC, merged