Feature/95386
prefeiturasp/SME-CDEP pull request #38
Opened 2023-06-23 13:20 UTC by viniciusnyari

AB#95386

2023-06-26 12:00 UTC, rafalosiamcom requested changes

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Webapi/Controllers/UsuarioController.cs
> +    [HttpPut("alterar-email")]
se o verbo é PUT não precisa do alterar- na rota.

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Webapi/Controllers/UsuarioController.cs
> +    public async Task<IActionResult> AlterarEmail(string login, string email, [FromServices] IServicoUsuario servicoUsuario)
o login deveria fazer parte da rota para ficar mais auto-explicativo
PUT v1/usuarios/{login}/email

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Webapi/Controllers/UsuarioController.cs
> +    [HttpPut("alterar-telefone")]
remover o alterar da rota

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs
> +        }
Remover async e await

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Aplicacao/Dtos/EnderecoTelefoneUsuarioExternoDTO.cs
> +        public string? Complemento { get; set; }
Esse atributo é nullable mas o complemento na entidade usuário não

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
> +                throw new NegocioException(MensagemNegocio.SO_EH_PERMITIDO_ALTERAR_ENDERECO_TELEFONE_DE_USUARIOS_EXTERNOS);
Código duplicado. Pode virar uma função privada

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
>                  throw new NegocioException(MensagemNegocio.A_SENHA_DEVE_CONTER_SOMENTE);
A validação de senha deve verificar todos os critérios não atendidos e retornar uma erro só.

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.TipoUsuario == TipoUsuario.PROFESSOR);
Esse código não esta verificando nada

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.Telefone.Equals(ConstantesTestes.TELEFONE_99_99999_9998));
Esse código não esta verificando nada

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.TipoUsuario == TipoUsuario.CORESSO);
Esse código não esta verificando nada

2023-06-26 12:00 UTC, rafalosiamcom commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.TipoUsuario == TipoUsuario.CORESSO);
Esse código não esta verificando nada

2023-06-26 12:18 UTC, viniciusnyari commented on SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
> +            var retorno = await servicoAcessos.AlterarEmail(login, email);
Ajustado

2023-06-26 12:23 UTC, viniciusnyari commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.TipoUsuario == TipoUsuario.PROFESSOR);
Está validando a alteração de endereço, tem uma diferença de um número, antes final 99 e agora final 98

2023-06-26 12:23 UTC, viniciusnyari commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.TipoUsuario == TipoUsuario.CORESSO);
Está garantindo que deu a exceção e que os dados não foram alterados

2023-06-26 12:24 UTC, viniciusnyari commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.TipoUsuario == TipoUsuario.CORESSO);
Mesmo caso do anterior. Dá a exceção, por que não pode alterar e vlaida se ao final a informação não foi alterada

2023-06-26 12:25 UTC, viniciusnyari commented on SME.CDEP.TesteIntegracao/Usuarios/Ao_cadastrar_usuario_externo.cs
> +            usuarios.FirstOrDefault(f => f.Telefone.Equals(ConstantesTestes.TELEFONE_99_99999_9998));
Está alterando o telefone de final 99 para 98

2023-06-26 14:25 UTC, viniciusnyari commented on SME.CDEP.Webapi/Controllers/UsuarioController.cs
> +    public async Task<IActionResult> AlterarEmail(string login, string email, [FromServices] IServicoUsuario servicoUsuario)
Ajustado

2023-06-26 18:48 UTC, rafalosiamcom requested changes

2023-06-26 20:56 UTC, viniciusnyari commented on SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs
> +                JsonConvert.SerializeObject(new { login, senhaAtual, senhaNova, sistemaId = Sistema_Cdep }));
Ajustado

2023-06-26 20:57 UTC, viniciusnyari commented on SME.CDEP.Aplicacao/Integracoes/ServicoAcessos.cs
> +            return await InvocarPutServicoAcessosRetornandoBool("v1/usuarios/email", JsonConvert.SerializeObject(new { login, email }));
Ajustado

2023-06-26 20:57 UTC, viniciusnyari commented on SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
> +            if (!retorno.Result)
Ajustado

2023-06-26 20:57 UTC, viniciusnyari commented on SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
> +            var retorno = servicoAcessos.AlterarSenha(login, senhaAtual, senhaNova);
Ajustado

2023-06-26 20:58 UTC, viniciusnyari commented on SME.CDEP.Aplicacao/Servicos/ServicoUsuario.cs
> +            var retorno = await servicoAcessos.AlterarEmail(login, email);
Ajustado

2023-06-27 17:01 UTC, rafalosiamcom approved these changes

2023-06-27 17:02 UTC, merged